{% set name = "ytree" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ytree-{{ version }}.tar.gz
  sha256: 4e929763e05d1e414f9f9c683450ca15fe0c116cd965cf52efe32f2685b38a9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - configparser
    - h5py
    - more-itertools >=8.4
    - numpy
    - python >=3.7
    - unyt
    - yt >=4.0

test:
  imports:
    - ytree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ytree-project/ytree
  summary: An extension of yt for working with merger tree data.
  dev_url: https://github.com/ytree-project/ytree
  license: BSD-3-Clause
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - brittonsmith
